# Generated by Django 3.0.8 on 2020-09-23 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posting',
        ),
    ]
